//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    static readonly ExplosiveComponent ExplosiveComponent = new ExplosiveComponent();

    public bool isExsplosive {
        get { return HasComponent(GameComponentsLookup.Exsplosive); }
        set {
            if (value != isExsplosive) {
                var index = GameComponentsLookup.Exsplosive;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : ExplosiveComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherExsplosive;

    public static Entitas.IMatcher<GameEntity> Exsplosive {
        get {
            if (_matcherExsplosive == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Exsplosive);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherExsplosive = matcher;
            }

            return _matcherExsplosive;
        }
    }
}
