//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.EventSystemsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Entitas;
using Entitas.Generics;
using UnityEngine.SocialPlatforms.Impl;

//public class GenericFeature : Feature
//{
//    public void GenerateEventSystems()
//    {
//        foreach
//    }
//}

public sealed class GameStateEventSystems : Feature {

    public GameStateEventSystems(GenericContexts contexts)
    {
        //Add(new ActionCountEventSystem(contexts)); // priority: 0
        //Add(new GameOverRemovedEventSystem(contexts)); // priority: 0
        //Add(new GameOverEventSystem(contexts)); // priority: 0
        //Add(new ScoreEventSystem(contexts)); // priority: 0

        Add(EventSystemFactory.Create<GameStateEntity, ScoreComponent>(contexts.GameState));
        Add(EventSystemFactory.Create<GameStateEntity, GameOverComponent>(contexts.GameState, GroupEvent.Added));
        Add(EventSystemFactory.Create<GameStateEntity, GameOverComponent>(contexts.GameState, GroupEvent.Removed));
        Add(EventSystemFactory.Create<GameStateEntity, ActionCountComponent>(contexts.GameState));

        //Add(new GenericEventSystem<GameStateEntity, ScoreComponent, 
        //    ListenerHolderComponent<GameStateEntity, ScoreComponent>>(contexts.GenericTemp.GameState));
    }
}

